services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=8 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  ipsec:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec
    env_file: ipsec.env
    restart: always
    volumes:
      - ./ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true